- name: update apt
  apt: update_cache=yes
- name: install libaio1
  apt: name=libaio1 state=latest

- name: create user group mysql
  shell: groupadd mysql
- name: create user msyql
  shell: useradd -r -g mysql -s /bin/false mysql

- name: unarchive mysql package
  unarchive: src=mysql-5.7.32-linux-glibc2.12-x86_64.tar.gz dest=/usr/local/
- name: ln
  shell: ln -s /usr/local/mysql-5.7.32-linux-glibc2.12-x86_64 /usr/local/mysql

- name: create dir
  file: path=/usr/local/mysql/mysql-files state=directory mode=750

- name: chown mysql-files
  shell: chown mysql:mysql /usr/local/mysql/mysql-files

- name: initialize mysql
  shell: /usr/local/mysql/bin/mysqld --initialize --user=mysql > /tmp/mysql_password.txt 2>&1
- name: mysql_ssl_rsa_setup
  shell: /usr/local/mysql/bin/mysql_ssl_rsa_setup
- name: execute mysqld_safe
  shell: /usr/local/mysql/bin/mysqld_safe --user=mysql &

- name: vim profile
  shell: echo 'export PATH=$PATH:/usr/local/mysql/bin' >> /etc/profile

- name: copy mysqld
  shell: cp /usr/local/mysql/support-files/mysql.server /etc/init.d/mysqld

- name: enable service
  shell: systemctl enable mysqld.service
- name: start mysqld
  shell: systemctl start mysqld

- name: get password
  shell: awk '/password/ {print $11}' /tmp/mysql_password.txt
  register: password

- name: change password
  shell: source /etc/profile && mysql -uroot -p"{{ password.stdout }}" --connect-expired-password -e "SET PASSWORD=PASSWORD('123456');flush privileges;"
